"""Fit the isotonic calibration from a generated validation set and store it.

Accuracy and calibration are different properties. The synthetic set shows the
method ranks the true vessel first almost always; this asks the other question
-- when it says 0.7, is it right about seven times in ten? -- and fits the
monotonic mapping that makes the reported number mean what it says.

Everything here is computed from the runs on disk. Nothing is hardcoded, and the
reliability bins the UI renders are the ones produced below.
"""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.score.calibrate import fit, uncalibrated_report  # noqa: E402


def collect(payload: dict) -> tuple[np.ndarray, np.ndarray]:
    """One (predicted probability, was-correct) pair per hypothesis considered.

    Both the winning and the losing hypotheses count. Calibrating only on the
    top-ranked one would measure a different, easier question than the one an
    analyst actually asks of a probability in the ranking.
    """
    probabilities: list[float] = []
    outcomes: list[float] = []

    for case in payload.get("cases", []):
        true_mmsi = case["true_mmsi"]
        probabilities.append(float(case["top_probability"]))
        outcomes.append(1.0 if case["top_mmsi"] == true_mmsi else 0.0)
        if case.get("true_probability") is not None and case["top_mmsi"] != true_mmsi:
            probabilities.append(float(case["true_probability"]))
            outcomes.append(1.0)
        probabilities.append(float(case["p_null"]))
        outcomes.append(0.0)  # the true vessel WAS in the set, so H0 is wrong here

    for case in payload.get("negative_controls", []):
        # The true vessel was removed, so H0 is the correct answer.
        probabilities.append(float(case["p_null"]))
        outcomes.append(1.0)
        probabilities.append(float(case["top_probability"]))
        outcomes.append(0.0)

    return np.asarray(probabilities, dtype=float), np.asarray(outcomes, dtype=float)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--set", type=Path, default=Path("fixtures/scenarios/synthetic_set.json"))
    parser.add_argument("--out", type=Path, default=Path("fixtures/scenarios/calibration.json"))
    parser.add_argument("--store", action="store_true", help="also write the record to the database")
    args = parser.parse_args()

    if not args.set.exists():
        raise SystemExit(f"no validation set at {args.set}; run scripts/make_synthetic_set.py first")

    payload = json.loads(args.set.read_text(encoding="utf-8"))
    probabilities, outcomes = collect(payload)
    print(f"collected {len(probabilities)} (probability, outcome) pairs "
          f"from {payload['n_cases']} cases and {payload['n_negative_controls']} negative controls")

    before = uncalibrated_report(probabilities, outcomes)
    notes = (
        f"Computed on {payload['n_cases']} synthetic attribution cases and "
        f"{payload['n_negative_controls']} negative controls generated by "
        f"scripts/make_synthetic_set.py. The slick in each case was simulated under one "
        f"forcing realisation and attributed under another. AIS tracks are real "
        f"({payload.get('ais_source', {}).get('source', 'unknown source')}); the slick is not. "
        f"These figures describe the method's internal consistency, not validation against "
        f"adjudicated real-world MARPOL cases -- no corpus of those exists at a scale that "
        f"would support such a claim."
    )
    report, _model = fit(probabilities, outcomes, notes=notes)

    print(f"  uncalibrated   Brier {before['brier_score']:.4f}   ECE {before['expected_calibration_error']:.4f}")
    print(f"  calibrated     Brier {report.brier:.4f}   ECE {report.ece:.4f}   (held-out n={report.n_cases})")

    # Apply the mapping only if it actually helps on held-out data. On this
    # synthetic set the raw posterior is already well calibrated -- the system
    # is confident and correct -- so isotonic regression fitted on half the
    # points adds noise rather than removing bias. Shipping a "calibration" that
    # makes the numbers worse in order to be able to say the word would be
    # exactly the kind of decoration this project is trying not to produce.
    applied = report.ece < before["expected_calibration_error"]
    if applied:
        headline = {"brier_score": round(report.brier, 5),
                    "expected_calibration_error": round(report.ece, 5),
                    "bins": report.bins, "n_cases": report.n_cases}
        rationale = "Isotonic regression is applied: it lowered ECE on the held-out split."
    else:
        headline = {"brier_score": before["brier_score"],
                    "expected_calibration_error": before["expected_calibration_error"],
                    "bins": before["bins"], "n_cases": before["n_cases"]}
        rationale = (
            f"Isotonic regression is NOT applied. Fitted on a held-out split it raised ECE "
            f"from {before['expected_calibration_error']:.4f} to {report.ece:.4f}, so the raw "
            f"posterior is reported instead. The mapping is stored below for inspection. "
            f"Read this as a property of this validation set rather than a general result: "
            f"the decoy vessels here are drawn at random, so the true source usually stands "
            f"out clearly, and a harder set with near-duplicate tracks would very likely need "
            f"the correction."
        )
    print(f"  {'applying' if applied else 'NOT applying'} the isotonic mapping")

    notes = f"{notes} {rationale}"
    record = {
        "id": uuid.uuid4().hex[:16],
        **headline,
        "isotonic": {"x": report.isotonic_x, "y": report.isotonic_y, "applied": applied},
        "isotonic_metrics": {"brier_score": round(report.brier, 5),
                             "expected_calibration_error": round(report.ece, 5),
                             "n_cases": report.n_cases},
        "uncalibrated": before,
        "notes": notes,
        "source_set": str(args.set),
        "top1_accuracy": payload["top1_accuracy"],
        "negative_control_pass_rate": payload["negative_control_pass_rate"],
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(record, indent=2), encoding="utf-8")
    print(f"  written to {args.out}")

    if args.store:
        from api.app.db import SessionLocal, create_all
        from api.app.models.records import CalibrationRecord

        create_all()
        with SessionLocal() as session:
            session.merge(CalibrationRecord(
                id=record["id"],
                n_cases=record["n_cases"],
                brier=record["brier_score"],
                ece=record["expected_calibration_error"],
                bins=record["bins"],
                isotonic=record["isotonic"],
                notes=notes,
            ))
            session.commit()
        print("  stored in the database")


if __name__ == "__main__":
    main()
