import type { Page, Route } from '@playwright/test'
import { expect } from '@playwright/test'

/** Deterministic stand-ins for the AVANTA API.
 *
 *  Shapes are copied from web/src/lib/types.ts and verified against live
 *  responses from api/app/routers/*.py, so a spec that passes here is a spec
 *  that would pass against the real backend for the same data.
 */

export const SCENE_ID = 'e2e5cene00000001'
export const RUN_ID = 'e2e7run000000001'
export const TOP_MMSI = '419000123'
export const SECOND_MMSI = '419000456'
export const DARK_MMSI = 'DARK-000001'

export const ROUTES = {
  watch: '/',
  scene: `/scene/${SCENE_ID}`,
  attribution: `/attribution/${RUN_ID}`,
  dossier: `/dossier/${RUN_ID}/${TOP_MMSI}`,
  calibration: '/calibration',
  about: '/about',
  notFound: '/no-such-console-screen',
} as const

export type RouteName = keyof typeof ROUTES
export const ALL_ROUTES = Object.keys(ROUTES) as RouteName[]

/* ------------------------------------------------------------------ */
/* Payloads                                                            */
/* ------------------------------------------------------------------ */

export const health = () => ({
  status: 'ok',
  version: '1.0.0',
  git_sha: 'e2e0000000000000',
  config_sha: '63ceb1311e88c59e1a64580a55442a2e6216444dc7a9f745f4c612a4465bc4ee',
  dependencies: {
    db: { status: 'UP' },
    cdse: { status: 'CONFIGURED', detail: 'Sentinel-1 GRD via the Sentinel Hub Process API' },
    forcing: { status: 'UP', wind: 'ERA5 reanalysis via the Open-Meteo archive API' },
    ais: {
      status: 'NOT_CONFIGURED',
      configured: false,
      connected: false,
      bbox: null,
      vessels: 0,
      messages_seen: 0,
      last_message_utc: null,
    },
    model: { segmenter: 'classical detector (no trained checkpoint loaded)' },
  },
})

export const scenarios = () => ({
  scenarios: [
    {
      id: 'elsa3',
      title: 'MSC ELSA 3',
      subtitle: 'Validation against a known source',
      kind: 'validation',
      label: 'VALIDATION CASE — known source position and time.',
      honesty_note: 'The source position, time and vessel identity are all public.',
      bbox: [75.6, 8.9, 76.5, 9.8],
      known_source: { lon: 76.136, lat: 9.3125, utc: '2025-05-25T02:20:00Z', vessel: 'MSC ELSA 3' },
      t_from: '2025-05-25T00:00:00Z',
      t_to: '2025-05-29T00:00:00Z',
    },
    {
      id: 'live',
      title: 'Live',
      subtitle: 'Current acquisition, live AIS',
      kind: 'live',
      label: 'LIVE — most recent Sentinel-1 pass and current AIS traffic.',
      honesty_note: 'This may legitimately return no slick, which is a correct result.',
      bbox: [70.2, 18.4, 71.6, 19.6],
      known_source: null,
      t_from: null,
      t_to: null,
    },
    {
      id: 'synthetic-discharge',
      title: 'Synthetic discharge',
      subtitle: 'The enforcement case, with exact ground truth',
      kind: 'synthetic',
      label: 'SYNTHETIC SLICK — ground truth is exact.',
      honesty_note: 'The slick was generated by simulating a discharge along one real track.',
      bbox: [70.2, 18.4, 71.6, 19.6],
      known_source: null,
      t_from: null,
      t_to: null,
    },
  ],
})

export const passingWindGate = () => ({
  wind_speed_ms: 6.4,
  wind_direction_deg: 241.0,
  min_ms: 3.0,
  max_ms: 10.0,
  passed: true,
  verdict:
    '6.4 m/s — inside the 3–10 m/s band where oil damps capillary waves enough to read as a dark region on radar, so an absence of contrast here is informative.',
  source: 'ERA5 (Open-Meteo archive)',
})

export const provenance = () => ({
  sar: {
    source: 'CDSE Sentinel Hub Process API (sentinel-1-grd, IW, DV, sigma0)',
    mode: 'CACHED',
    sha256: '6f8c3b6886b6d7229950d5fa6f5adc11c9ac9d5150c334fb46a91e525164f18a',
  },
  wind: { source: 'ERA5 (Open-Meteo archive)', mode: 'CACHED', sha256: '90a8e0ef9308f4a3' },
  code: { git_sha: 'e2e0000000000000', config_sha: '63ceb1311e88c59e' },
  run_utc: '2025-05-28T02:00:00+00:00',
})

export const scenes = () => ({
  scenes: [
    {
      id: SCENE_ID,
      scenario: 'synthetic-discharge',
      bbox: [70.2, 18.4, 71.6, 19.6],
      acquired_utc: '2025-05-28T00:41:37+00:00',
      mode: 'SYNTHETIC',
      status: 'NEW',
      wind_gate: passingWindGate(),
      n_slicks: 1,
      created_at: '2025-05-28T00:52:36.392450',
    },
    {
      id: 'e2e5cene00000002',
      scenario: 'elsa3',
      bbox: [75.6, 8.9, 76.5, 9.8],
      acquired_utc: '2025-05-28T00:41:37+00:00',
      mode: 'CACHED',
      status: 'GATED',
      wind_gate: {
        wind_speed_ms: 12.07,
        wind_direction_deg: 274.0,
        min_ms: 3.0,
        max_ms: 10.0,
        passed: false,
        verdict: '12.1 m/s — above the 10 m/s detection ceiling.',
        source: 'ERA5 (Open-Meteo archive)',
      },
      n_slicks: 0,
      created_at: '2025-05-28T00:12:36.392450',
    },
  ],
})

export const scene = () => ({
  id: SCENE_ID,
  scenario: 'synthetic-discharge',
  bbox: [70.2, 18.4, 71.6, 19.6],
  t_from: '2025-05-27T00:00:00Z',
  t_to: '2025-05-29T00:00:00Z',
  acquired_utc: '2025-05-28T00:41:37+00:00',
  product_id: 'S1A_IW_GRDH_1SDV_20250528T004137_E8F1_COG.SAFE',
  mode: 'SYNTHETIC',
  status: 'NEW',
  wind_gate: passingWindGate(),
  provenance: provenance(),
  n_slicks: 1,
  created_at: '2025-05-28T00:52:36.392450',
})

const reasons = (supportsOil: boolean) => [
  {
    feature: 'area_km2',
    value: supportsOil ? 4.82 : 0.61,
    threshold: 1.0,
    weight: 1.4,
    comparison: 'ge',
    passed: supportsOil,
    supports: supportsOil ? 'oil' : 'look_alike',
    note: 'Large contiguous dark areas are consistent with a spreading discharge.',
  },
  {
    feature: 'elongation',
    value: supportsOil ? 8.1 : 1.2,
    threshold: 3.0,
    weight: 1.8,
    comparison: 'ge',
    passed: supportsOil,
    supports: supportsOil ? 'oil' : 'look_alike',
    note: 'A discharge under way lays oil along the track, producing a long narrow region.',
  },
  {
    feature: 'edge_gradient',
    value: supportsOil ? 0.44 : 0.08,
    threshold: 0.2,
    weight: 1.1,
    comparison: 'ge',
    passed: supportsOil,
    supports: supportsOil ? 'oil' : 'look_alike',
    note: 'Oil has a sharp boundary; a low-wind cell fades into the background.',
  },
]

export const detections = () => ({
  detections: {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        id: 1,
        geometry: {
          type: 'Polygon',
          coordinates: [[[70.8, 18.9], [71.2, 19.0], [71.22, 19.04], [70.82, 18.94], [70.8, 18.9]]],
        },
        properties: {
          class: 'oil',
          confidence: 0.87,
          area_km2: 4.82,
          centroid: [71.01, 18.97],
          major_axis_deg: 74.0,
          major_axis_length_km: 42.6,
          features: { area_km2: 4.82, elongation: 8.1, edge_gradient: 0.44 },
          reasons: reasons(true),
        },
      },
      {
        type: 'Feature',
        id: 2,
        geometry: {
          type: 'Polygon',
          coordinates: [[[70.4, 18.6], [70.5, 18.6], [70.5, 18.7], [70.4, 18.7], [70.4, 18.6]]],
        },
        properties: {
          class: 'look_alike',
          confidence: 0.31,
          area_km2: 0.61,
          centroid: [70.45, 18.65],
          major_axis_deg: 12.0,
          major_axis_length_km: 3.1,
          features: { area_km2: 0.61, elongation: 1.2, edge_gradient: 0.08 },
          reasons: reasons(false),
        },
      },
    ],
  },
  ship_contacts: [
    { lon: 70.94, lat: 18.99 },
    { lon: 71.15, lat: 19.12 },
  ],
  wind_gate: passingWindGate(),
  mode: 'SYNTHETIC',
  provenance: provenance(),
})

export const emptyDetections = () => ({
  detections: { type: 'FeatureCollection', features: [] },
  ship_contacts: [],
  wind_gate: passingWindGate(),
  mode: 'SYNTHETIC',
  provenance: provenance(),
})

const succeededJob = (kind: string, result: Record<string, unknown>) => ({
  job_id: `job-${kind}`,
  kind,
  status: 'succeeded',
  stage: 'complete',
  progress: 1,
  result,
  error: null,
  log: [`${kind} finished`],
})

export const jobs = {
  ingest: () => succeededJob('ingest', { scene_id: SCENE_ID, mode: 'SYNTHETIC' }),
  candidates: () => succeededJob('candidates', { scene_id: SCENE_ID, n_candidates: 3 }),
  attribution: () => succeededJob('attribution', { run_id: RUN_ID, scene_id: SCENE_ID }),
}

/* Evidence terms are constructed so that, for every candidate:
 *    sum(likelihood terms) === log_likelihood
 *    sum(prior terms)      === log_prior
 *    sum(all terms)        === score
 * which is exactly the invariant core/score/attribute.py asserts. */
const evidenceFor = (
  likelihood: [string, number, string][],
  prior: [string, number, string][],
) => {
  const terms = [
    ...likelihood.map(([name, value, explanation]) => ({ group: 'likelihood' as const, name, value, explanation })),
    ...prior.map(([name, value, explanation]) => ({ group: 'prior' as const, name, value, explanation })),
  ]
  const round6 = (n: number) => Number(n.toFixed(6))
  const logL = round6(likelihood.reduce((a, [, v]) => a + v, 0))
  const logPi = round6(prior.reduce((a, [, v]) => a + v, 0))
  return {
    terms,
    sum: round6(logL + logPi),
    score: round6(logL + logPi),
    log_likelihood: logL,
    log_prior: logPi,
  }
}

const TOP_EVIDENCE = evidenceFor(
  [
    ['coverage', -11.4, 'Log density of simulated oil under the pixels where oil was observed.'],
    ['false_area_penalty', -3.2, 'Penalty for simulated oil landing where none was observed.'],
    ['ensemble_marginalisation', -0.4, 'Adjustment from marginalising over 8 ensemble members with perturbed wind and current forcing.'],
  ],
  [
    ['ship_type', 0.6, 'Tankers discharge oily bilge water more often than the fleet average.'],
    ['ais_gap', 0.4, 'A transmission gap overlaps the maximum-likelihood release window.'],
  ],
)

const SECOND_EVIDENCE = evidenceFor(
  [
    ['coverage', -13.0, 'Log density of simulated oil under the pixels where oil was observed.'],
    ['false_area_penalty', -2.4, 'Penalty for simulated oil landing where none was observed.'],
    ['ensemble_marginalisation', -0.1, 'Adjustment from marginalising over 8 ensemble members.'],
  ],
  [['ship_type', 0.5, 'General cargo vessels are a middling prior for an oily-water discharge.']],
)

const DARK_EVIDENCE = evidenceFor(
  [
    ['coverage', -16.0, 'Log density of simulated oil under the pixels where oil was observed.'],
    ['false_area_penalty', -1.5, 'Penalty for simulated oil landing where none was observed.'],
    ['ensemble_marginalisation', -0.2, 'Adjustment from marginalising over 8 ensemble members.'],
  ],
  [['dark_contact', 0.3, 'A radar contact with no matching AIS transmission raises the prior.']],
)

const track = (lon: number, lat: number) => ({
  type: 'FeatureCollection' as const,
  features: [
    {
      type: 'Feature' as const,
      properties: { segment: 'transmitted', is_dark: false, mmsi: TOP_MMSI },
      geometry: {
        type: 'LineString' as const,
        coordinates: [[lon, lat], [lon + 0.2, lat + 0.05], [lon + 0.4, lat + 0.11]],
      },
    },
  ],
})

const SLICK = {
  type: 'FeatureCollection' as const,
  features: [
    {
      type: 'Feature' as const,
      properties: { class: 'oil', area_km2: 4.82 },
      geometry: {
        type: 'Polygon' as const,
        coordinates: [[[70.8, 18.9], [71.2, 19.0], [71.22, 19.04], [70.82, 18.94], [70.8, 18.9]]],
      },
    },
  ],
}

const release = (start: string, end: string) => ({
  t_start: start,
  t_end: end,
  duration_hours: 2.5,
  rate_m3_per_h: 1.8,
  volume_m3: 4.5,
  oil_type: 'GENERIC INTERMEDIATE FUEL OIL 180',
})

const seed = () => ({
  n_elements: 4800,
  n_vertices: 48,
  n_per_point: 100,
  distinct_seed_positions: 48,
  distinct_seed_times: 48,
  degenerate: false,
  degenerate_reason: null,
})

const candidateList = () => [
  {
    mmsi: TOP_MMSI,
    name: 'MT ANJALI',
    ship_type: 'Tanker',
    is_dark: false,
    release: release('2025-05-27T20:10:00Z', '2025-05-27T22:40:00Z'),
    seed: seed(),
    log_likelihood: TOP_EVIDENCE.log_likelihood,
    log_prior: TOP_EVIDENCE.log_prior,
    score: TOP_EVIDENCE.score,
  },
  {
    mmsi: SECOND_MMSI,
    name: 'MV KAVERI STAR',
    ship_type: 'Cargo',
    is_dark: false,
    release: release('2025-05-27T19:00:00Z', '2025-05-27T21:30:00Z'),
    seed: seed(),
    log_likelihood: SECOND_EVIDENCE.log_likelihood,
    log_prior: SECOND_EVIDENCE.log_prior,
    score: SECOND_EVIDENCE.score,
  },
  {
    mmsi: DARK_MMSI,
    name: null,
    ship_type: 'Unknown',
    is_dark: true,
    release: release('2025-05-27T18:20:00Z', '2025-05-27T20:50:00Z'),
    seed: seed(),
    log_likelihood: DARK_EVIDENCE.log_likelihood,
    log_prior: DARK_EVIDENCE.log_prior,
    score: DARK_EVIDENCE.score,
  },
]

/** Attribution with a clear winner: p(H0) is small and vessels rank above it. */
export const attribution = () => ({
  run_id: RUN_ID,
  scene_id: SCENE_ID,
  candidate_set_id: 'cset-e2e-0001',
  acquisition_utc: '2025-05-28T00:41:37+00:00',
  posterior: {
    entries: [
      {
        hypothesis_id: TOP_MMSI,
        label: `MT ANJALI (${TOP_MMSI})`,
        probability: 0.612,
        log_likelihood: TOP_EVIDENCE.log_likelihood,
        log_prior: TOP_EVIDENCE.log_prior,
        score: TOP_EVIDENCE.score,
        is_null: false,
        rank: 1,
        is_dark: false,
        ship_type: 'Tanker',
      },
      {
        hypothesis_id: SECOND_MMSI,
        label: `MV KAVERI STAR (${SECOND_MMSI})`,
        probability: 0.229,
        log_likelihood: SECOND_EVIDENCE.log_likelihood,
        log_prior: SECOND_EVIDENCE.log_prior,
        score: SECOND_EVIDENCE.score,
        is_null: false,
        rank: 2,
        is_dark: false,
        ship_type: 'Cargo',
      },
      {
        hypothesis_id: DARK_MMSI,
        label: `Dark contact ${DARK_MMSI}`,
        probability: 0.081,
        log_likelihood: DARK_EVIDENCE.log_likelihood,
        log_prior: DARK_EVIDENCE.log_prior,
        score: DARK_EVIDENCE.score,
        is_null: false,
        rank: 3,
        is_dark: true,
        ship_type: 'Unknown',
      },
      {
        hypothesis_id: 'H0',
        label: 'H0 — source not among the candidates',
        probability: 0.078,
        log_likelihood: -19.4,
        log_prior: -0.9,
        score: -20.3,
        is_null: true,
        rank: 4,
      },
    ],
    p_null: 0.078,
    no_attribution: false,
    h0_threshold: 0.5,
    sums_to: 1.0,
  },
  candidates: candidateList(),
  null: { log_likelihood: -19.4, log_prior: -0.9, model: 'diffuse null over the search box' },
  ensemble_spread: {
    [TOP_MMSI]: { median: 0.61, lo: 0.48, hi: 0.72, n: 8, width: 24 },
    [SECOND_MMSI]: { median: 0.23, lo: 0.14, hi: 0.31, n: 8, width: 18 },
    [DARK_MMSI]: { median: 0.08, lo: 0.02, hi: 0.15, n: 8, width: 12 },
  },
  evidence: {
    [TOP_MMSI]: TOP_EVIDENCE,
    [SECOND_MMSI]: SECOND_EVIDENCE,
    [DARK_MMSI]: DARK_EVIDENCE,
  },
  tracks: {
    [TOP_MMSI]: track(70.7, 18.86),
    [SECOND_MMSI]: track(70.6, 19.02),
    [DARK_MMSI]: track(70.5, 18.78),
  },
  slick: SLICK,
  wind_gate: passingWindGate(),
  grid: { shape: [128, 128], downsample_factor: 4, slick_cells: 212 },
  provenance: provenance(),
  runtime_s: 42.7,
})

/** Attribution where the null hypothesis wins: p(H0) > 0.5, so the console
 *  must refuse to rank any vessel above it. */
export const noAttribution = () => {
  const base = attribution()
  const entries = [
    {
      hypothesis_id: 'H0',
      label: 'H0 — source not among the candidates',
      probability: 0.634,
      log_likelihood: -12.1,
      log_prior: -0.4,
      score: -12.5,
      is_null: true,
      rank: 1,
    },
    { ...base.posterior.entries[0], probability: 0.201, rank: 2 },
    { ...base.posterior.entries[1], probability: 0.108, rank: 3 },
    { ...base.posterior.entries[2], probability: 0.057, rank: 4 },
  ]
  return {
    ...base,
    posterior: {
      entries,
      p_null: 0.634,
      no_attribution: true,
      h0_threshold: 0.5,
      sums_to: 1.0,
    },
  }
}

/** Attribution with no candidate vessels at all — only the null hypothesis. */
export const emptyAttribution = () => {
  const base = noAttribution()
  return {
    ...base,
    posterior: { ...base.posterior, entries: [base.posterior.entries[0]] },
    candidates: [],
    evidence: {},
    tracks: {},
    ensemble_spread: {},
  }
}

export const simulation = () => ({
  release: release('2025-05-27T20:10:00Z', '2025-05-27T22:40:00Z'),
  seed: seed(),
  frames: [
    {
      t: '2025-05-27T22:40:00Z',
      n: 3,
      lon: [70.82, 70.9, 70.98],
      lat: [18.91, 18.95, 18.99],
      mass_kg: 3960,
    },
    {
      t: '2025-05-27T23:40:00Z',
      n: 3,
      lon: [70.85, 70.94, 71.03],
      lat: [18.92, 18.96, 19.01],
      mass_kg: 3720,
    },
    {
      t: '2025-05-28T00:41:00Z',
      n: 3,
      lon: [70.88, 70.99, 71.09],
      lat: [18.93, 18.98, 19.03],
      mass_kg: 3510,
    },
  ],
  oil: { density_kg_m3: 962, viscosity_cst: 180 },
})

export const candidates = () => ({
  scene_id: SCENE_ID,
  mode: 'SYNTHETIC',
  results: [
    {
      mmsi: TOP_MMSI,
      name: 'MT ANJALI',
      ship_type: 'Tanker',
      is_dark: false,
      total_score: 3.2,
      kept: true,
      closest_approach_km: 2.4,
      terms: [
        { name: 'proximity', value: 2.4, score: 1.8, explanation: 'Closest approach to the slick.' },
        { name: 'ship_type', value: 1, score: 1.4, explanation: 'Tanker.' },
      ],
    },
  ],
  dark_contacts: [],
})

export const dossier = () => ({
  run_id: RUN_ID,
  mmsi: TOP_MMSI,
  pdf_url: `/api/v1/dossier/${RUN_ID}/${TOP_MMSI}/pdf`,
  json_url: `/api/v1/dossier/${RUN_ID}/${TOP_MMSI}/json`,
  html_url: `/api/v1/dossier/${RUN_ID}/${TOP_MMSI}/html`,
  manifest_sha256: 'a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90',
  fields: {
    section_1_observation: {
      date_and_time_utc: '2025-05-28T00:41:37Z',
      position: '18.97 N, 71.01 E',
      observer: 'AVANTA automated watch',
      weather_and_sea_state: 'Wind 6.4 m/s from 241 degrees, ERA5 reanalysis',
    },
    section_2_appearance: {
      appearance_of_discharge: 'Continuous dark linear region, 42.6 km along its major axis',
      area_km2: 4.82,
      photographs_taken: false,
      samples_taken: 'NOT AVAILABLE',
    },
    section_3_vessel: {
      vessel_name: 'MT ANJALI',
      mmsi: TOP_MMSI,
      imo: 'NOT AVAILABLE',
      flag_state: 'NOT AVAILABLE',
      ship_type: 'Tanker',
    },
    section_4_evidence: {
      posterior_probability: 0.612,
      p_unknown_source: 0.078,
      method: 'Forward simulation of each candidate track, scored against the observed slick',
      ensemble_members: 8,
    },
  },
})

export const handoff = () => ({
  run_id: RUN_ID,
  mmsi: TOP_MMSI,
  domain_check: { inside: true, message: 'Release point is inside the OOSA v4.0 domain.' },
  release: {
    lon: 70.82,
    lat: 18.91,
    start_utc: '2025-05-27T20:10:00Z',
    end_utc: '2025-05-27T22:40:00Z',
    volume_m3: 4.5,
    oil_type: 'GENERIC INTERMEDIATE FUEL OIL 180',
  },
})

export const calibration = () => ({
  brier_score: 0.0834,
  expected_calibration_error: 0.0421,
  n_cases: 240,
  computed_at: '2025-05-20T11:02:00Z',
  notes:
    'Fitted on 240 generated cases where the true source vessel is known exactly, with the slick simulated under one forcing realisation and attributed under another.',
  bins: [
    { lo: 0.0, hi: 0.2, count: 61, mean_predicted: 0.09, observed_frequency: 0.11 },
    { lo: 0.2, hi: 0.4, count: 48, mean_predicted: 0.29, observed_frequency: 0.27 },
    { lo: 0.4, hi: 0.6, count: 44, mean_predicted: 0.51, observed_frequency: 0.48 },
    { lo: 0.6, hi: 0.8, count: 52, mean_predicted: 0.7, observed_frequency: 0.73 },
    { lo: 0.8, hi: 1.0, count: 35, mean_predicted: 0.91, observed_frequency: 0.89 },
  ],
})

export const emptyCalibration = () => ({ ...calibration(), n_cases: 0, bins: [] })

/* ------------------------------------------------------------------ */
/* Routing                                                             */
/* ------------------------------------------------------------------ */

export type StubKey =
  | 'health'
  | 'scenarios'
  | 'scenes'
  | 'scene'
  | 'detections'
  | 'raster'
  | 'ingest'
  | 'candidatesGenerate'
  | 'candidates'
  | 'attributionRun'
  | 'attribution'
  | 'simulation'
  | 'job'
  | 'dossier'
  | 'handoff'
  | 'calibration'

export interface Reply {
  status?: number
  json?: unknown
  body?: string
  contentType?: string
}

export type Handler = Reply | ((context: { url: URL; method: string; key: StubKey }) => Reply | Promise<Reply>)

/** Map a request onto one of the stub keys, or null when it is not an API call. */
export function classify(url: URL, method: string): StubKey | null {
  const p = url.pathname
  if (!p.startsWith('/api/v1/')) return null
  if (p === '/api/v1/health') return 'health'
  if (p === '/api/v1/scenarios') return 'scenarios'
  if (p === '/api/v1/scenes') return 'scenes'
  if (p === '/api/v1/scenes/ingest' && method === 'POST') return 'ingest'
  if (p.endsWith('/raster.png')) return 'raster'
  if (/^\/api\/v1\/scenes\/[^/]+\/detections$/.test(p)) return 'detections'
  if (/^\/api\/v1\/scenes\/[^/]+$/.test(p)) return 'scene'
  if (p === '/api/v1/candidates/generate') return 'candidatesGenerate'
  if (p === '/api/v1/candidates') return 'candidates'
  if (p === '/api/v1/attribution/run') return 'attributionRun'
  if (/^\/api\/v1\/attribution\/[^/]+\/sim\/.+$/.test(p)) return 'simulation'
  if (/^\/api\/v1\/attribution\/[^/]+$/.test(p)) return 'attribution'
  if (/^\/api\/v1\/jobs\/[^/]+$/.test(p)) return 'job'
  if (p.startsWith('/api/v1/dossier')) return 'dossier'
  if (p === '/api/v1/handoff/oosa') return 'handoff'
  if (p === '/api/v1/calibration') return 'calibration'
  return null
}

const DEFAULTS: Record<StubKey, () => Reply> = {
  health: () => ({ json: health() }),
  scenarios: () => ({ json: scenarios() }),
  scenes: () => ({ json: scenes() }),
  scene: () => ({ json: scene() }),
  detections: () => ({ json: detections() }),
  // The SAR raster is a basemap underlay. Nothing in the suite reads its
  // pixels, and the app is written to degrade when it cannot be fetched, so
  // it is refused rather than faked with a binary body.
  raster: () => ({ status: 404, json: { detail: 'Raster imagery is not served in the test harness.' } }),
  ingest: () => ({ json: { job_id: 'job-ingest' } }),
  candidatesGenerate: () => ({ json: { job_id: 'job-candidates' } }),
  candidates: () => ({ json: candidates() }),
  attributionRun: () => ({ json: { job_id: 'job-attribution' } }),
  attribution: () => ({ json: attribution() }),
  simulation: () => ({ json: simulation() }),
  job: () => ({ json: jobs.ingest() }),
  dossier: () => ({ json: dossier() }),
  handoff: () => ({ json: handoff() }),
  calibration: () => ({ json: calibration() }),
}

async function fulfil(route: Route, reply: Reply) {
  const headers: Record<string, string> = {
    'access-control-allow-origin': '*',
    'access-control-allow-headers': '*',
    'access-control-allow-methods': 'GET,POST,OPTIONS',
    'cache-control': 'no-store',
  }
  if (reply.json !== undefined) {
    await route.fulfill({
      status: reply.status ?? 200,
      contentType: 'application/json',
      headers,
      body: JSON.stringify(reply.json),
    })
    return
  }
  await route.fulfill({
    status: reply.status ?? 200,
    contentType: reply.contentType ?? 'text/plain',
    headers,
    body: reply.body ?? '',
  })
}

/** Install the API stub. Overrides replace a single endpoint's behaviour. */
export async function stubApi(page: Page, overrides: Partial<Record<StubKey, Handler>> = {}) {
  await page.route('**/api/v1/**', async (route) => {
    const request = route.request()
    const method = request.method()
    const url = new URL(request.url())
    if (method === 'OPTIONS') {
      await fulfil(route, { status: 204, body: '' })
      return
    }
    const key = classify(url, method)
    if (key === null) {
      await fulfil(route, { status: 404, json: { detail: `No stub for ${method} ${url.pathname}` } })
      return
    }
    const override = overrides[key]
    const reply =
      override === undefined
        ? DEFAULTS[key]()
        : typeof override === 'function'
          ? await override({ url, method, key })
          : override
    await fulfil(route, reply)
  })
}

/** Jobs are polled by followJob(); dispatch on the job id the app was given. */
export const jobRouter: Handler = ({ url }) => {
  const id = url.pathname.split('/').pop() ?? ''
  if (id.includes('candidates')) return { json: jobs.candidates() }
  if (id.includes('attribution')) return { json: jobs.attribution() }
  return { json: jobs.ingest() }
}

/** An HTTP 500 whose body carries the real reason, the way the API reports one. */
export const serverError = (detail: string): Reply => ({ status: 500, json: { detail } })

/** Keep the basemap off the network.
 *
 *  The tile server is refused rather than mirrored: the map is documented to
 *  degrade to a flat dark ground with every data layer still rendering, and
 *  the suite should exercise that rather than depend on a third-party CDN. */
export async function stubMapTiles(page: Page) {
  await page.route('**/services.arcgisonline.com/**', (route) => route.abort())
}

/* ------------------------------------------------------------------ */
/* Shared assertions                                                   */
/* ------------------------------------------------------------------ */

/** Anchors that prove a route has actually finished rendering. */
export async function waitForRoute(page: Page, name: RouteName) {
  switch (name) {
    case 'watch':
      await expect(page.getByTestId('scenario-list')).toBeVisible()
      break
    case 'scene':
      await expect(page.locator('.analysis-layout, [role="alert"], [role="status"]').first()).toBeVisible()
      break
    case 'attribution':
      await expect(page.locator('.attribution-layout, [role="alert"], [role="status"]').first()).toBeVisible()
      break
    case 'dossier':
      await expect(page.locator('.record-page, [role="alert"], [role="status"]').first()).toBeVisible()
      break
    case 'calibration':
      await expect(page.locator('.record-page, [role="alert"], [role="status"]').first()).toBeVisible()
      break
    case 'about':
      await expect(page.getByRole('heading', { name: 'Method', exact: true })).toBeVisible()
      break
    case 'notFound':
      await expect(page.getByRole('heading', { name: 'No such page' })).toBeVisible()
      break
  }
}

/** Anchors that prove a route has rendered its actual data, not a placeholder.
 *  Used wherever a measurement (contrast, geometry) has to be taken against
 *  real content rather than a skeleton. */
export async function waitForContent(page: Page, name: RouteName) {
  switch (name) {
    case 'watch':
      await expect(page.getByTestId('alert-row').first()).toBeVisible()
      await expect(page.getByTestId('run-scenario-elsa3')).toBeVisible()
      break
    case 'scene':
      await expect(page.getByTestId('wind-gate')).toBeVisible()
      await expect(page.getByTestId('lookalike-panel')).toBeVisible()
      break
    case 'attribution':
      await expect(page.getByTestId('h0-row')).toBeVisible()
      await expect(page.getByTestId('candidate-row').first()).toBeVisible()
      await expect(page.getByTestId('timeline')).toBeVisible()
      break
    case 'dossier':
      await expect(page.getByTestId('download-pdf')).toBeVisible()
      await expect(page.getByRole('heading', { name: 'Vessel' })).toBeVisible()
      break
    case 'calibration':
      await expect(page.getByTestId('reliability-diagram')).toBeVisible()
      break
    case 'about':
      await expect(page.getByRole('heading', { name: 'Method', exact: true })).toBeVisible()
      await expect(page.getByRole('heading', { name: 'Runtime capability' })).toBeVisible()
      break
    case 'notFound':
      await expect(page.getByRole('heading', { name: 'No such page' })).toBeVisible()
      break
  }
}

/** Navigate and wait until the route's content is on screen and settled. */
export async function goto(page: Page, name: RouteName) {
  await page.goto(ROUTES[name])
  await waitForRoute(page, name)
  await settle(page)
}

/** Navigate and wait until the route's real data has rendered and settled. */
export async function gotoReady(page: Page, name: RouteName) {
  await page.goto(ROUTES[name])
  await waitForContent(page, name)
  await settle(page)
}

/** Wait until every finite animation has finished.
 *
 *  Entry animations fade text in from zero opacity. Measuring colour contrast
 *  or geometry part-way through one reads a value that exists for a few frames
 *  and depends entirely on when the frame was sampled. Waiting for the
 *  animations to finish is what makes those measurements mean something. */
export async function settle(page: Page) {
  await page.waitForFunction(
    () =>
      document
        .getAnimations()
        .filter((animation) => {
          const timing = animation.effect?.getComputedTiming()
          return timing !== undefined && timing.iterations !== Infinity
        })
        .every((animation) => animation.playState === 'finished' || animation.playState === 'idle'),
    undefined,
    { timeout: 10_000 },
  )
}

const JUNK = ['undefined', 'NaN', '[object Object]'] as const

/** No placeholder ever reaches the analyst's screen. */
export async function expectNoRenderedJunk(page: Page, where: string) {
  const text = await page.evaluate(() => document.body.innerText)
  for (const needle of JUNK) {
    expect(
      text.includes(needle),
      `${where}: rendered text must not contain the literal "${needle}".\n` +
        `Offending excerpt: ${excerpt(text, needle)}`,
    ).toBe(false)
  }
}

function excerpt(text: string, needle: string): string {
  const at = text.indexOf(needle)
  if (at < 0) return '(none)'
  return JSON.stringify(text.slice(Math.max(0, at - 90), at + needle.length + 90))
}

/** The interface renders a true minus sign (U+2212) for negatives. */
export function parseSignedNumber(text: string): number {
  const normalised = text.trim().replace(/\u2212/g, '-').replace(/^\+/, '')
  const value = Number(normalised)
  expect(Number.isFinite(value), `expected a number, got ${JSON.stringify(text)}`).toBe(true)
  return value
}
